# Generated by Django 5.1.3 on 2024-11-27 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0002_attempt_questionoption_respondent_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('score', models.TextField(null=True)),
                ('strength', models.TextField(null=True)),
                ('weakness', models.TextField(null=True)),
                ('long_term_goal', models.TextField(null=True)),
                ('short_term_goal', models.TextField(null=True)),
                ('conclusion', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_attempt', to='quize.attempt')),
            ],
        ),
    ]
