# Generated by Django 4.2.16 on 2024-11-27 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0003_quiz_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='attempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attempt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
