# Generated by Django 5.1.3 on 2024-11-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0003_aireport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aireport',
            name='analysis',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='conclusion',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='long_term_goal',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='score',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='short_term_goal',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='strength',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='summary',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='weakness',
            field=models.JSONField(null=True),
        ),
    ]
