# Generated by Django 5.1.3 on 2024-11-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0004_alter_aireport_analysis_alter_aireport_conclusion_and_more'),
        ('quize', '0004_alter_response_options_attempt_created_at_and_more'),
    ]

    operations = [
    ]
