# Generated by Django 5.1.3 on 2024-11-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0005_merge_20241128_0059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={},
        ),
        migrations.RenameField(
            model_name='aireport',
            old_name='analysis',
            new_name='analysis_reposrt',
        ),
        migrations.RemoveField(
            model_name='aireport',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='aireport',
            name='long_term_goal',
        ),
        migrations.RemoveField(
            model_name='aireport',
            name='score',
        ),
        migrations.RemoveField(
            model_name='aireport',
            name='short_term_goal',
        ),
        migrations.RemoveField(
            model_name='aireport',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='aireport',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='aireport',
            name='weakness',
        ),
    ]
