# Generated by Django 5.1.3 on 2024-11-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0006_alter_quiz_options_alter_response_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aireport',
            old_name='analysis_reposrt',
            new_name='analysis_report',
        ),
    ]
