# Generated by Django 4.2.16 on 2024-12-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0008_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
