# Generated by Django 4.2.16 on 2024-12-02 17:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0009_product_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aireport',
            name='analysis_report',
        ),
        migrations.AddField(
            model_name='aireport',
            name='roadmap',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='aireport',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_report', to='quize.attempt'),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aireport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
